### ISSUE TITLE
Warning: comparison between signed and unsigned integer expression

### ISSUE THREAD

**Issue by carneeki** [tardate/X113647Stepper#2]
When compiling with Arduino 1.6.10 for the 2560 or 328 I get the following warning appear:

```
X113647Stepper.cpp: In member function 'void X113647Stepper::setSpeed(float)':
X113647Stepper.cpp:107:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(this->step_delay < this->minimum_delay) this->step_delay = this->minimum_delay;
```

By changing `X113647Stepper.minimum_delay` in the header to type `unsigned int` this goes away. It also makes sense that numbers always >= 0 be unsigned.

Thanks :)
Adam

**Comment by tardate** [comment]
@carneeki thanks for catching and reporting the issue! I'll go dig out some steppers shortly and test the fix.

**Comment by tardate** [comment]
thanks, should be fixed
