### ISSUE TITLE
Can X113647 be used for bipolar 4-wire motor ?

### ISSUE THREAD

**Issue by jiapei100** [tardate/X113647Stepper#5]
What is the difference between X113647 and L298N?
Can a X113647 be used for driving a DVD motor?

**Comment by tardate** [comment]
Sorry I can't comment on the L298N - no experience with that.

> Can the X113647 be used for DVD motor? 

Most likely. The X113647 is a pretty generic ULN2003A-based board, so as long as the DVD stepper is 4-wire control, should work if you get the connections and sequence right.

best of luck in hacking that;-)
